spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?profileSQL=true
    username: threadly
    password: localpwd
    hikari:
      maximum-pool-size: 25
      minimum-idle: 0
      connection-timeout: 5000
      validation-timeout: 1000
      idle-timeout: 300000
      max-lifetime: 1700000
      keepalive-time: 120000
      auto-commit: false

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    open-in-view: false
  #    show-sql: true

  flyway:
    locations: classpath:flyway
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
