spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?profileSQL=true
    username: test
    password: test
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false

