#DEV
services:
  postgresql:
    container_name: threadly-postgresql-test
    image:
      postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: threadly
      POSTGRES_USER: threadly
      POSTGRES_PASSWORD: localpwd
    volumes:
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly-service/infra/volumes/postgres_dev/data:/var/lib/postgresql/data
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly-service/logs/postgres:/var/log

  redis-test:
    container_name: threadly-redis-test
    image: redis:latest
    command: [ "redis-server", "--logfile", "/var/log/redis.log" ]
    volumes:
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly-service/infra/volumes/redis/data:/data
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly-service/logs/redis:/var/log
    ports:
      - "6380:6379"

  pushgateway:
    image: prom/pushgateway:latest
    platform: linux/arm64
    restart: always
    ports:
      - '9091:9091'
    networks:
      - monitoring-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly-service/infra/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring-network

  zookeeper:
    container_name: zookeeper-dev
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    container_name: kafka-dev
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network


networks:
  monitoring-network:
    external: true
  kafka-network:
    external: true
