services:
  app:
    image: threadly-app-local:latest
    build:
      context: ..
      dockerfile: infra/Dockerfile
      args:
        CACHE_BREAKER: 1
    depends_on:
      - postgresql
      - redis
    working_dir: /app
    command: [ "java", "-jar", "/app/threadly.jar" ]
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    volumes:
      - ../logs:/app/logs
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
    stdin_open: true
    networks:
      - threadly-network

  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: threadly
      POSTGRES_USER: threadly
      POSTGRES_PASSWORD: localpwd
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ../logs:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - threadly-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: [ "redis-server", "--logfile", "/var/log/redis/redis.log" ]
    volumes:
      - ./data/redis:/data
      - ../logs:/var/log/redis
    ports:
      - "6379:6379"
    networks:
      - threadly-network

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-stack/loki/config.yml:/etc/loki/config.yml
      - ./loki-stack/loki/data:/tmp/loki
      - ./loki-stack/loki/wal:/wal
    command: -config.file=/etc/loki/config.yml
    networks:
      - threadly-network

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ../logs:/app/logs
      - ./loki-stack/promtail/config_local.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - threadly-network

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - threadly-network

volumes:
  grafana-storage:

networks:
  threadly-network:
    driver: bridge
