version: "3.8"

services:
  app:
    image: kimgyubek/threadly-app
    container_name: threadly-app
    depends_on:
      - postgresql
      - redis
    working_dir: /app
    command: [ "java", "-jar", "threadly.jar" ]
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    networks:
      - threadly-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: threadly
      POSTGRES_USER: threadly
      POSTGRES_PASSWORD: localpwd
    volumes:
      - /home/ubuntu/docker-volumes/postgres:/var/lib/postgresql/data
    networks:
      - threadly-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - /home/ubuntu/docker-volumes/redis:/data
    networks:
      - threadly-network

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-stack/loki/config.yml:/etc/loki/config.yml
      - /home/ubuntu/docker-volumes/loki/data:/tmp/loki
      - /home/ubuntu/docker-volumes/loki/wal:/wal
    command: -config.file=/etc/loki/config.yml

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/hostname:/etc/hostname:ro
      - ./loki-stack/promtail/config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_PASSWORD=admin
    volumes:
      - /home/ubuntu/docker-volumes/grafana:/var/lib/grafana

volumes:
  grafana-storage:

networks:
  threadly-network:
    driver: bridge
