version: "3.8"

services:
  app:
    image: threadly-app
#    build:
#      dockerfile: ./infra/Dockerfile
#      context: ../
    container_name: threadly-app
    depends_on:
      - postgresql
      - redis
    working_dir: /app
    command: [ "java", "-jar", "/app/threadly.jar" ]
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    networks:
      - threadly-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
    stdin_open: true

  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: threadly
      POSTGRES_USER: threadly
      POSTGRES_PASSWORD: localpwd
    volumes:
      - ./data/db_local:/var/lib/postgresql/data
    networks:
      - threadly-network
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - threadly-network
    ports:
      - "6379:6379"

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-stack/loki/config.yml:/etc/loki/config.yml
      - ./loki-stack/loki/data:/tmp/loki
      - ./loki-stack/loki/wal:/wal
    command: -config.file=/etc/loki/config.yml

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /etc/hostname:/etc/hostname
      - ./loki-stack/promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

networks:
  threadly-network:
    driver: bridge
