version: "3.8"

services:
  app:
    image: threadly-app-prod
    container_name: threadly-app
    depends_on:
      - postgresql
      - redis
    working_dir: /app
    command: [ "java", "-jar", "threadly.jar" ]
    ports:
      - "8080:8080"
    env_file:
      - ./infra/.env
    networks:
      - threadly-network

  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: threadly
      POSTGRES_USER: threadly
      POSTGRES_PASSWORD: localpwd
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - threadly-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - threadly-network

networks:
  threadly-network:
    driver: bridge
