FROM gradle:8.4.0-jdk21 AS builder
ARG CACHE_BREAKE

WORKDIR /app

COPY build.gradle settings.gradle.kts gradle.properties ./
COPY gradle ./gradle

RUN echo "CACHE_BREAKER=$CACHE_BREAKER" && ./gradlew dependencies --no-daemon  || true

COPY . .

RUN ./gradlew clean :threadly-apps:app-api:bootJar -x test --no-daemon

RUN ls -al /app/threadly-apps/app-api/build/libs

FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY --from=builder /app/threadly-apps/app-api/build/libs/app*.jar /app/threadly.jar

ENTRYPOINT ["java", "-jar", "/app/threadly.jar"]

