services:
  app:
    image: threadly-app
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - h2
      - redis
      - redis-test
    environment:
      - mail.name=rlarbqor00@naver.com
      - mail.password=Z38NR6QCKD7K
      - spring.profiles.active=prod
      - spring.data.redis.host=redis
      - spring.data.redis.port=6379
#      - spring.config.import=optional:classpath:application-persistence-prod.yml,optional:classpath:application-redis-prod.yml,optional:classpath:application-port.yml
    networks:
      - threadly-network

  postgresql:
    image:
      postgres:16
    restart: always
    volumes:
      - ./data/threadly-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: localpwd
    networks:
      - threadly-network

  h2:
    image: oscarfonts/h2
    platform: linux/amd64
    environment:
      - H2_OPTIONS=-mem -tcp -tcpAllowOthers -webAllowOthers
    ports:
      - "9092:9092"
      - "8082:8082"  # H2 웹 콘솔 포트
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/threadly-redis:/data
    networks:
      - threadly-network

  redis-test:
    image: redis:latest
    container_name: threadly-redis-test
    ports:
      - "6380:6379"



  prometheus:
    image: prom/prometheus:v2.29.1
    platform: linux/arm64
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  pushgateway:
    image: prom/pushgateway:latest
    platform: linux/arm64
    restart: always
    ports:
      - '9091:9091'

  grafana:
    image: grafana/grafana:6.0.2
    restart: always
    ports:
      - '3000:3000'
networks:
  threadly-network:
