version: "3.8"

services:
  app:
    image: openjdk:17-jdk
    container_name: threadly-app
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./threadly.jar:/app/threadly.jar
    working_dir: /app
    command: [ "java", "-jar", "threadly.jar" ]
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/threadly
      SPRING_DATASOURCE_USERNAME: threadly
      SPRING_DATASOURCE_PASSWORD: localpwd
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - threadly-network

  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: threadly
      POSTGRES_USER: threadly
      POSTGRES_PASSWORD: localpwd
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - threadly-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - threadly-network

networks:
  threadly-network:
    driver: bridge
