version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ../Dockerfile.local
    container_name: threadly-app
    depends_on:
      - postgresql
      - redis
    working_dir: /runner
    command: [ "java", "-jar", "threadly.jar" ]
    ports:
      - "8080:8080"
    env_file:
      - ./.env.local
    networks:
      - threadly-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: threadly
      POSTGRES_USER: threadly
      POSTGRES_PASSWORD: localpwd
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - threadly-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - threadly-network

networks:
  threadly-network:
    driver: bridge
