spring:
  batch:
    job:
      enabled: true
  config:
    import:
      - "classpath:application-persistence-dev.yml"
logging:
  level:
    root: info
    org.springframework.boot.autoconfigure.batch: debug
    com.threadly.batch: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

properties:
  retention:
    image:
      deleted: PT72H
      temporary: PT24H
    post:
      deleted: P30D
    user:
      deleted: P180D
