spring:
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: never

prometheus:
  job:
    name: pushgateway
  pushgateway:
    url: localhost:9091

logging:
  level:
    com.threadly.batch.listener: INFO
    com.threadly.batch: DEBUG
    org.springframework.batch: INFO


