services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: threadly
      POSTGRES_USER: threadly
      POSTGRES_PASSWORD: localpwd
    volumes:
      - /home/ubuntu/docker-volumes/postgres:/var/lib/postgresql/data
      - /home/ubuntu/threadly/logs/services/postgres:/var/log
    user: "999:999"
    ports:
      - "5432:5432"
    networks:
      - threadly-network
      - monitoring-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - /home/ubuntu/docker-volumes/redis:/data
      - /home/ubuntu/threadly/logs/services/redis:/var/log
    user: "999:999"
    ports:
      - "6379:6379"
    command: [ "redis-server", "--logfile", "/var/log/redis.log" ]
    networks:
      - service-network


networks:
  monitoring-network:
    external: true
  service-network:
    external: true
