logging:
  level:
    root: warn
    com.threadly: info
    org.springframework: warn
    org.hibernate.SQL: warn
    org.hibernate.type.descriptor.sql.BasicBinder: warn

properties:
  ttl:
    access-token: 900
    refresh-token: 1209600
    blacklist-token: 900
    email-verification: 600
    password-verification: 600
