spring:
  config:
    import:
      - adapter-persistence-test.yml
      - adapter-redis.yml
      - core-port.yml

logging:
  level:
    root: info
    com.threadly: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace