spring:
  config:
    import:
#      - "classpath:application-.yml"
      - "classpath:application-redis-dev.yml"
      - "classpath:application-port.yml"
logging:
  level:
    root: info
    com.threadly: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

properties:
  ttl:
    access-token: 600
    refresh-token: 3600
    blacklist-token: 600
    email-verification: 300
    password-verification: 300
