logging:
  level:
    root: info
    com.threadly: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

properties:
  ttl:
    access-token: 15000
    refresh-token: 60000
    blacklist-token: 15000
    email-verification: 15000
    password-verification: 5000
