spring:
  config:
    import:
      - "classpath:application-redis-dev.yml"
      - "classpath:application-persistence-dev.yml"
      - "classpath:application-port.yml"
logging:
  level:
    root: info
    com.threadly: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

properties:
  ttl:
    access-token: 600
    refresh-token: 3600
    blacklist-token: 600
    email-verification: 300
    password-verification: 300
    login-attempt: 300
    post-view: 3600
  file:
    upload:
      location: ./local-storage/uploads/images/
      access-url: http://localhost:8080/images/

