services:
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - /home/ubuntu/threadly/infra/loki-stack/loki/config.yml:/etc/loki/config.yml
      - /home/ubuntu/docker-volumes/loki/data:/tmp/loki
      - /home/ubuntu/docker-volumes/loki/wal:/wal
    command: -config.file=/etc/loki/config.yml
    networks:
      - monitoring-network

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /home/ubuntu/threadly/logs:/app/logs
      - /home/ubuntu/threadly/infra/loki-stack/promtail/config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_PASSWORD=admin
    volumes:
      - /home/ubuntu/docker-volumes/grafana:/var/lib/grafana
    networks:
      - monitoring-network

  promehteus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/threadly/infra/config/prometheus.prod.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      threadly-network:
      monitoring-network:

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    pid: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:r0
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    networks:
      monitoring-network:



volumes:
  grafana-storage:

networks:
  threadly-network:
    external: true
  monitoring-network:
    external: true
