services:
  app:
    image: threadly-app-local:latest
    build:
      context: /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly
      dockerfile: infra/docker/app/Dockerfile
      args:
        CACHE_BREAKER: 1
    depends_on:
      - postgresql
      - redis
    working_dir: /app
    command: [ "java", "-jar", "/app/threadly.jar" ]
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    volumes:
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly/logs/app:/app/logs
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
    stdin_open: true
    environment:
      TZ: "Asia/Seoul"
    networks:
      - threadly-network

  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: threadly
      POSTGRES_USER: threadly
      POSTGRES_PASSWORD: localpwd
    volumes:
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly/infra/volumes/postgres/data:/var/lib/postgresql/data
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly/logs/postgres:/var/log
    ports:
      - "5432:5432"
    networks:
      - threadly-network
      - monitoring-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: [ "redis-server", "--logfile", "/var/log/redis.log" ]
    volumes:
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly/infra/volumes/redis/data:/data
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly/logs/redis:/var/log
    ports:
      - "6379:6379"
    networks:
      - threadly-network

networks:
  monitoring-network:
    external: true
  threadly-network:
    driver: bridge
