#DEV
services:
  postgresql:
    container_name: threadly-postgresql-test
    image:
      postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: threadly
      POSTGRES_USER: threadly
      POSTGRES_PASSWORD: localpwd
    volumes:
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly/infra/volumes/postgres/data:/var/lib/postgresql/data
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly/logs/postgres:/var/log


  h2:
    container_name: threadly-h2-test
    image: oscarfonts/h2
    platform: linux/amd64
    environment:
      - H2_OPTIONS=-mem -tcp -tcpAllowOthers -webAllowOthers
    ports:
      - "9092:9092"
      - "8082:8082"  # H2 웹 콘솔 포트
    restart: unless-stopped

  redis-test:
    container_name: threadly-redis-test
    image: redis:latest
    command: [ "redis-server", "--logfile", "/var/log/redis.log" ]
    volumes:
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly/infra/volumes/redis/data:/data
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly/logs/redis:/var/log
    ports:
      - "6380:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly/infra/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring-network

networks:
  monitoring-network:
    external: true
