services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: threadly
      POSTGRES_USER: threadly
      POSTGRES_PASSWORD: localpwd
    volumes:
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly-service/infra/volumes/postgres/data:/var/lib/postgresql/data
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly-service/logs/postgres:/var/log
    ports:
      - "5432:5432"
    networks:
      - service-network
      - monitoring-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: [ "redis-server", "--logfile", "/var/log/redis.log" ]
    volumes:
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly-service/infra/volumes/redis/data:/data
      - /Users/gimgyubaeg/workspace/java/project/ecommerce/threadly-service/logs/redis:/var/log
    ports:
      - "6379:6379"
    networks:
      - service-network

networks:
  monitoring-network:
    external: true
  service-network:
    external: true
