spring:
  mail:
    host: smtp.naver.com
    port: 587
    username: rlarbqor00@naver.com
    password: Z38NR6QCKD7K
    properties:
      mail:
        smtp:
          debug: true
          auth: true
        starttls:
          enable: true
mail:
  from: rlarbqor00@naver.com