name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t threadly-app-prod -f ./Dockerfile .

      - name: Save Docker image to tar
        run: |
          rm -f threadly-app.tar
          docker save threadly-app-prod -o threadly-app.tar
          chmod 644 threadly-app.tar

      - name: Debug file list
        run: ls -al && ls -al infra

      - name: Copy Docker image and compose file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: |
            threadly-app.tar
            ./infra/docker-compose.prod.yml
          target: "~/threadly"
          tar_dereference: false

      - name: SSH into EC2 and load + run image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd ~/threadly
            docker load -i threadly-app.tar
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d